@startuml Gestion de Pedidos Restaurante

title Gestion de Pedidos Restaurante

abstract class Pedido {


    -productos: Comida[]
    -numeroPedido: string
    -estadoPedido: 

    +agregarProducto(producto: Comida)

}

class Salon extends Pedido{
    -mesa: string
    -mozo: Empleado
}

class Delivery extends Pedido{
    -cadete: Empleado
    -direccion: string
    -costoEnvio: number
}

class ParaLlevar extends Pedido{

    -horario: time

}

class Menu {

    -items: Comida[]
    +agregarItem(item: Comida)
    +quitarItem(item:Comida)

}
abstract class Comida {
    -disponible: boolean
    -nombre: string
    -precio: number
    //definir este metodo en esta clase(como se vaya a usar en Item) y se sobreescribe en Combo
    +chequearEstado()

}
class Combo extends Comida {

  // se inicializa con array de items vacio 
  // opciones: 2 constructores o un metodo que inicialice
    -porcentaje: number = PORCENTAJEFIJO
    -items: Item[]

    //sobreescribir metodo chequearEstado: en esta clase recorre el array y ve todos los estados de los items
    +agregarItem(item: Item)
    +eliminarItem(item: Item)
    +calcularPrecio()
}

class Item extends Comida{
    -estacion: Estacion
    -estado: 

}


abstract class Estacion {
    -
    +modificarEstadoItem()
}
class CocinaFria extends Estacion{

}

class Carnes extends Estacion{

}
class Barra extends Estacion{

}
class CocinaDulce extends Estacion{

}

interface enConstruccion {

}

abstract class Empleado {
    - nombre: string
    - cuil: number
    - sector: string
}

class Mozo extends Empleado {
    
}
class Cadete extends Empleado {
    
}

Salon --> enConstruccion

@enduml